apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lgtm-stack.fullname" . }}
  labels:
    {{- include "lgtm-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lgtm-stack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lgtm-stack.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        {{- if .Values.healthCheck.enabled }}
        livenessProbe:
          {{- toYaml .Values.healthCheck.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.healthCheck.readinessProbe | nindent 10 }}
        {{- end }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
        - name: ASPNETCORE_URLS
          value: {{ .Values.env.ASPNETCORE_URLS | quote }}
        - name: Serilog__WriteTo__1__Args__uri
          value: {{ .Values.app.lokiEndpoint | quote }}
        - name: Serilog__WriteTo__1__Args__labels__1__value
          value: {{ .Values.app.labels.environment | quote }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.app.otlpEndpoint | quote }}
        volumeMounts:
        - name: config
          mountPath: /app/appsettings.Production.json
          subPath: appsettings.Production.json
          readOnly: true
        - name: tmp
          mountPath: /tmp
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "lgtm-stack.fullname" . }}-config
      - name: tmp
        emptyDir: {}